all: 
	cc  levelcheck.c ini.c get_player.c check_map.c loadmap.c mem.c colors_a.c colors_b.c get_colors.c get_map.c get_textures.c show.c utils.c ../../libs/libft/libft.a && ./a.out map1.cub

# -fsanitize=address -g